server:
  port: ${PORT}

spring:
  application:
    name: look

  datasource:
    username: ${DB_USERNAME}
    password: ${DP_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access_expiration_time: ${ACCESS_EXPIRATION_TIME}
  refresh_expiration_time: ${REFRESH_EXPIRATION_TIME}
