server:
  port: ${PORT}

spring:
  application:
    name: look
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: none
        show_sql: false
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - openid
              - profile_nickname
              - profile_image
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            jwk-set-uri: ${GOOGLE_JWK_SET_URI}
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            jwk-set-uri: ${KAKAO_JWK_SET_URI}

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          job-store-type: jdbc
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
      org.quartz.jobStore.dataSource: quartzDataSource
      org.quartz.dataSource.quartzDataSource.driver: org.mariadb.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: ${DB_URL}
      org.quartz.dataSource.quartzDataSource.user: ${DB_USERNAME}
      org.quartz.dataSource.quartzDataSource.password: ${DB_PASSWORD}
      org.quartz.dataSource.quartzDataSource.maxConnections: 10

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access_expiration_time: ${ACCESS_EXPIRATION_TIME}
  refresh_expiration_time: ${REFRESH_EXPIRATION_TIME}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}


weather:
  vilage-fcst-url: ${WEATHER_FCST_URL}
  service-key: ${WEATHER_SERVICE_KEY}