server:
  port: 8080

spring:
  application:
    name: look

  datasource:
    username: boram
    password: 1234
    url: jdbc:mariadb://localhost:3306/onthelook?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

springdoc:
  use-fqn: true

jwt:
  secret-key: "local-test"
  access_expiration_time: 3000
  refresh_expiration_time: 1209600000
